### ISSUE TITLE
Grade extraction fails

### ISSUE THREAD

**Issue by vilppuvuorinen** [lebseu/GPACalcVAMK#1]
Grade extraction fails if `Virt` or `T&K` fields are not empty.

Sample row:

```
[course] ([implementation])     OK [course id]  4,00 OP 1,00    2,00    5   [mail]  22.06.2014
```

First integer value of the row seems to be used instead of the grade.

**Comment by likair** [comment]
You are true. Thanks!

**Comment by likair** [comment]
Hi, I have fixed the bug. You can test it again.

**Comment by vilppuvuorinen** [comment]
It seems to be working. Finally GPA from CLI interface.
